version: "3.9"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass MEGA_SECRET_PASSWORD
    environment:
      REDIS_PASSWORD: MEGA_SECRET_PASSWORD