server:
  port: 7777


spring:
  kafka:
    bootstrap-servers:
      - localhost:80
    consumer:
      auto-offset-reset: latest
      group-id: friendly
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1
      fetch-max-wait: 36000
      enable-auto-commit: false
      client-id: friendly
    producer:
      client-id: friendly
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 2
    jaas:
      enabled: true
    listener:
      poll-timeout: 1800000
      concurrency: 1
      ack-mode: manual_immediate


  data:
    redis:
      host: localhost
      port: 6379
