basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a sample API for Gin framework.
  title: My Gin API
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: Возвращает строку "Привет, мир!"
      produces:
      - application/json
      responses:
        "200":
          description: Привет, мир!
          schema:
            type: string
      summary: Получить приветствие
      tags:
      - hello
swagger: "2.0"
